services:
  'AppBundle\Action\Contacts\TenantsEdit':
    class: AppBundle\Action\Contacts\TenantsEdit
    arguments:
      - "@=service('doctrine').getRepository('AppBundle:Tenant')"
      - "@router"
      - "@twig"

  'AppBundle\Action\Contacts\TenantsEditPersonal':
    class: AppBundle\Action\Contacts\TenantsEditPersonal
    arguments:
      - "@=service('doctrine').getRepository('AppBundle:Tenant')"
      - "@form.factory"
      - "@app.form_handler.generic"
      - "@router"
      - "@twig"
      - "@=service('session').getFlashBag()"
      - "@=service('security.token_storage').getToken().getUser()"

  'AppBundle\Action\Contacts\TenantsEditCriteria':
    class: AppBundle\Action\Contacts\TenantsEditCriteria
    arguments:
      - "@=service('doctrine').getRepository('AppBundle:Tenant')"
      - "@form.factory"
      - "@app.form_handler.generic"
      - "@router"
      - "@twig"
      - "@=service('session').getFlashBag()"
