imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
    locale: en_GB

framework:
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ['10.113.0.1', '10.113.0.201'] # Layershift
    session:
        name: GOLDENEAGLE
        handler_id: session.handler.native_file
        cookie_secure: true
    fragments:       ~
    http_method_override: true
    assets: ~

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    date:
        timezone: Europe/London
    form_themes:
         - 'bootstrap_3_horizontal_layout.html.twig'
         - 'Form/base.html.twig'
         - 'Form/collection-type.html.twig'
         - 'Form/phone-type.html.twig'

doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_bin
        types:
            phone_number: Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType
            json: Doctrine\DBAL\Types\JsonArrayType # Type json will be introduced in doctrine/dbal@2.6
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        mappings:
          AppBundle: ~
          FOSUserBundle: ~
          Money:
            type: yml
            dir: "%kernel.root_dir%/../app/Resources/MoneyMoney/doctrine"
            prefix: Money

stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            timestampable: true
            blameable: true

swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
  db_driver: orm
  firewall_name: main
  user_class: AppBundle\Entity\User

fos_js_routing:
  cache_control:
    public: false
    maxage: 3600
    smaxage: 3600
    expires: 60 minutes
    vary: [ Cookie ]

dunglas_action: ~

doctrine_date_time_immutable_types:
    register: replace
