app_controller:
  resource: "@AppBundle/Controller/"
  type:     annotation

app_explicit:
  resource: '@AppBundle/Resources/config/routing.yml'

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
  resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
