# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  'AppBundle\Action\Contacts\TenantsEdit':
    class: AppBundle\Action\Contacts\TenantsEdit
    arguments:
      - "@=service('doctrine').getRepository('AppBundle:Tenant')"
      - "@router"
      - "@twig"

  'AppBundle\Action\Contacts\TenantsEditPersonal':
    class: AppBundle\Action\Contacts\TenantsEditPersonal
    arguments:
      - "@=service('doctrine').getRepository('AppBundle:Tenant')"
      - "@form.factory"
      - "@app.form_handler.generic"
      - "@router"
      - "@twig"
      - "@=service('session').getFlashBag()"
      - "@=service('security.token_storage').getToken().getUser()"

  'AppBundle\Action\Contacts\TenantsEditCriteria':
    class: AppBundle\Action\Contacts\TenantsEditCriteria
    arguments:
      - "@=service('doctrine').getRepository('AppBundle:Tenant')"
      - "@form.factory"
      - "@app.form_handler.property_criteria"
      - "@router"
      - "@twig"
      - "@=service('session').getFlashBag()"

  'AppBundle\Action\Contacts\TenantsEditNotes':
    class: AppBundle\Action\Contacts\TenantsEditNotes
    arguments:
      - "@=service('doctrine').getRepository('AppBundle:Tenant')"
      - "@form.factory"
      - "@app.form_handler.generic"
      - "@router"
      - "@twig"
