app_applicants:
  path: /applicants
  defaults: { _controller: AppBundle\Action\Contacts\Applicants:__invoke }
  methods: [GET]

app_applicants_list:
  path: /applicants/list
  defaults: { _controller: AppBundle\Action\Contacts\ApplicantsList:__invoke }

app_tenants:
  path: /tenants
  defaults: { _controller: AppBundle\Action\Contacts\Tenants:__invoke }
  methods: [GET]

app_tenants_add:
  path: /tenants/add
  defaults: { _controller: AppBundle\Action\Contacts\TenantsAdd:__invoke }
  methods: [GET]

app_tenants_add_personal:
  path: /tenants/add/personal
  defaults: { _controller: AppBundle\Action\Contacts\TenantsEditPersonal:__invoke }
  methods: [GET, POST]

app_tenants_edit:
  path: /tenants/{tenantId}
  requirements:
    tenantId: \d+
  defaults: { _controller: AppBundle\Action\Contacts\TenantsEdit:__invoke }
  methods: [GET]
  options:
    expose: true

app_tenants_edit_personal:
  path: /tenants/{tenantId}/personal
  requirements:
    tenantId: \d+
  defaults: { _controller: AppBundle\Action\Contacts\TenantsEditPersonal:__invoke }
  methods: [GET,POST]

app_tenants_edit_criteria:
  path: /tenants/{tenantId}/criteria
  requirements:
    tenantId: \d+
  defaults: { _controller: AppBundle\Action\Contacts\TenantsEditCriteria:__invoke }
  methods: [GET,POST]

app_tenants_edit_notes:
  path: /tenants/{tenantId}/notes
  requirements:
    tenantId: \d+
  defaults: { _controller: AppBundle\Action\Contacts\TenantsEditNotes:__invoke }
  methods: [GET,POST]

app_tenants_edit_note_delete:
  path: /tenants/notes/{noteId}
  requirements:
    noteId: \d+
  defaults: { _controller: AppBundle\Action\Contacts\TenantsEditNotes:__invoke }
  methods: [DELETE]
